ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS company_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS tax_id VARCHAR(20),
    ADD COLUMN IF NOT EXISTS address_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS moo VARCHAR(50),
    ADD COLUMN IF NOT EXISTS village VARCHAR(255),
    ADD COLUMN IF NOT EXISTS soi VARCHAR(255),
    ADD COLUMN IF NOT EXISTS road VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sub_district VARCHAR(100),
    ADD COLUMN IF NOT EXISTS district VARCHAR(100),
    ADD COLUMN IF NOT EXISTS province VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
